# 1. The name of your automation
name: Daily Job Agent

# 2. When should this run?
on:
  schedule:
    - cron: '0 8 */2 * *'  # 8:00 AM on alternate days
      timezone: "Asia/Dubai"
  workflow_dispatch:      # This adds a "Run" button so you can test it manually

# 3. What should the computer do?
jobs:
  run-my-script:
    runs-on: ubuntu-latest  # Uses a fresh Linux machine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This "pulls" your code into the Linux machine

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get Gmail credentials from secrets & save to newly created files
        run: |
          mkdir -p secrets
          echo "${{ secrets.GMAIL_CREDENTIALS_B64 }}" | base64 -d > secrets/credentials.json    
          echo "${{ secrets.GMAIL_TOKEN_B64 }}" | base64 -d > secrets/token.json

      - name: Run the agent
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CANDIDATE_NAME: ${{ secrets.CANDIDATE_NAME }}
          CANDIDATE_EMAIL: ${{ secrets.CANDIDATE_EMAIL }}
          CANDIDATE_LINKEDIN_URL: ${{ secrets.CANDIDATE_LINKEDIN_URL }}
          CANDIDATE_GITHUB_URL: ${{ secrets.CANDIDATE_GITHUB_URL }}
          CANDIDATE_MOB_NO: ${{ secrets.CANDIDATE_MOB_NO }}
        run: python main.py

    - name: Commit and Push DB changes
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
            # Force add the database even if it was ignored before
            git add db/jobs.db 
            
            # Only commit if the file actually changed
            git commit -m "Update job database: $(date)" || echo "No new jobs found today"
            git push